package com.ssm.dao;

import com.ssm.bean.Emplovee;
import com.ssm.bean.EmploveeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmploveeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    long countByExample(EmploveeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int deleteByExample(EmploveeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int insert(Emplovee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int insertSelective(Emplovee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    List<Emplovee> selectByExample(EmploveeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    Emplovee selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Emplovee record, @Param("example") EmploveeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int updateByExample(@Param("record") Emplovee record, @Param("example") EmploveeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(Emplovee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Tue Aug 06 17:24:32 CST 2019
     */
    int updateByPrimaryKey(Emplovee record);
}